### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by retep998** [BurntSushi/chan-signal#1]
Windows does not have the signal handling mechanism of *nix. Instead it has two things:
1. `SetConsoleCtrlHandler` which catches things like `ctrl + C` in the command line.
2. Registering an SEH exception handler to catch certain kinds of SEH exceptions such as segfaults, illegal instructions, arithmetic interrupts, stuff like that. Could probably be done with `AddVectoredExceptionHandler`.

**Comment by BurntSushi** [comment]
Ah excellent, thanks for the info!

**Comment by dns2utf8** [comment]
I suddenly need this for a project, but right now I cant compile chan-signal on windows.

Are you still working on it?

**Comment by BurntSushi** [comment]
@dns2utf8 No. You might see if `ctrlc` can fit your use case instead.

**Comment by dns2utf8** [comment]
I tried it, but it does not work well with cargo.
Thank you for the information.

**Comment by jgraham** [comment]
#26 has a patch to fix this issue.

**Comment by BurntSushi** [comment]
This crate is now deprecated. See: https://users.rust-lang.org/t/ann-chan-is-deprecated-use-crossbeam-channel-instead/19251
