### ISSUE TITLE
Using longer constant names?

### ISSUE THREAD

**Issue by StefanoD** [BurntSushi/chan-signal#12]
INT and TERM are ambiguous. They have their own meanings. So you may want to rename them to INTERRUPT and TERMINATE, because we do have the possibility to spell them in full in the 21th century. If you look to the Apple API or Java API, this is really common and helps newcomers to better understand the code.

Proceed with other constants the same way like `SIGALRM`.

Consider to do a breaking change in order to have just one right way.

**Comment by BurntSushi** [comment]
Could you please explain why `INT` and `TERM` are ambiguous in this context?

**Comment by StefanoD** [comment]
For the first second I really thought INT means integer and then I read TERM and I asked myself what this could mean. But then I then I put this in the right context and remembered what they mean, because I handled this signal types many years ago in an OS course.
My opinion still is:
- This is not C where the first versions had limited variable name length
- Newcomers will have it easier
- Other API's like Java and Apple's API spell almost everything in full and there is a reason why. Because abbreviations are today unnecessary and spell in full more readable and comprehensible.

**Comment by BurntSushi** [comment]
I can appreciate that, but these are standard names and I'm not particularly comfortable changing them. I'd rather it be much simpler to line up the signals with, say, the output of `kill -l`.

Given the context of the enum's name, `Signal`, I don't think the names are ambiguous.

**Comment by rschmitt** [comment]
It looks like `INT` and `TERM` never appear in isolation in actual code; they appear as `Signal::INT` and `Signal::TERM` respectively. The only place where I see something like `INT` in isolation is in a few comments or strings, such as:

``` rust
    // Signal gets a value when the OS sent a INT or TERM signal.
```

I think that `SIGINT` is slightly preferable to "an INT signal," the former usage also being present in a few places, e.g.:

``` rust
// names if the user sends the process SIGINT or SIGTERM.
```

As an additional historical note, I believe that variable name length limitations were actually present in _linkers_, not the C language itself. I think that linkers were originally only guaranteed to be able to resolve symbol names based on the first six characters (case insensitive!), which explains names like `strcat` and `strncat` in the C standard library.
