### ISSUE TITLE
doesn't seem to work with `fork()`

### ISSUE THREAD

**Issue by philippkeller** [BurntSushi/chan-signal#13]
I'm trying to mix this chan module together with `libc::fork()` but somehow it doesn't work.
This is probably due to some difference between `thread::spawn()` and `fork()` but I just don't understand why it should not work.

[Here's](https://gist.github.com/philippkeller/38ff188ddb5aea01ce91ba5e00aefae2) the example from the README adapted to fork(). Interestingly the `INT` signal works but the `TERM` not even though `sdone` is really moved into `run`

(this issue moved from [here](https://github.com/BurntSushi/chan/issues/17))

**Comment by philippkeller** [comment]
I'm really a beginner in this concurrency topic so I can only utter wild guesses: Could it be that `fork()` with it's "copy on write" model actually copies the channel so the `TERM` signal is sent into another channel than the parent is running `recv` on? (this is assuming that Rusts threading does not do copy-on-write in threading)

**Comment by radupopescu** [comment]
Hi!

I'm having this issue, too.

After a call to `fork()`, I do:
```rust
    let signal = chan_signal::notify(&[Signal::CHLD, Signal::INT, Signal::TERM]);
    // Wait for a signal or for work to be done.
    chan_select! {
        signal.recv() -> signal => {
            println!("Received signal: {:?}", signal)
        },
    }
```
in the parent process. No signal is received from the child process, but the INT signal is received (I generate it when doing Ctrl-C to exit).

I'm on macOS 10.12, rust 1.14 and 1.16.0-nightly (83c2d9523 2017-01-24), chan 0.1.18, chan-signal 0.2.0.

Cheers,
Radu

**Comment by BurntSushi** [comment]
My guess is that this has to do with the child process not inheriting the signal masks.

**Comment by radupopescu** [comment]
@BurntSushi Could be. Is Signal::INT by default in the signal mask?
One question, though. Is the signal mask used in the child process? In my example it is the parent process which waits on the CHLD signal.

**Comment by BurntSushi** [comment]
I don't know. Someone needs to go learn about `pthread_sigmask` and its behavior across parent/child processes, which is used in this crate. It's my understanding that no signals are masked by default, which is why this crate demands that you run `chan_signal::notify` at the very beginning of your program.

There isn't much code in this crate, but I don't have time to investigate this issue myself right now.

**Comment by radupopescu** [comment]
@BurntSushi Thanks for the feedback. I need this kind of functionality for a project, so if I find something, I'll post back here.

Cheers,

**Comment by BurntSushi** [comment]
This crate is now deprecated. See: https://users.rust-lang.org/t/ann-chan-is-deprecated-use-crossbeam-channel-instead/19251
