### ISSUE TITLE
API for waiting on any signal

### ISSUE THREAD

**Issue by SamWhited** [BurntSushi/chan-signal#16]
It would be nice if there was an API for waiting on any signal (or just some straight forward way of getting a complete slice of the signal enum without manually typing them all out).

I've got a small application that's already got a signal mask set in libc land, and just need to receive any of the signals it can get.

**Comment by BurntSushi** [comment]
This crate is now deprecated. See: https://users.rust-lang.org/t/ann-chan-is-deprecated-use-crossbeam-channel-instead/19251
