### ISSUE TITLE
Can't catch Ignored signals

### ISSUE THREAD

**Issue by agatan** [BurntSushi/chan-signal#19]
`sigwait` can't catch ignored signals at least in macOS (e.g., `SIGIO` or `SIGWINCH`).
man page of `sigwait` notes:
> Processes which call sigwait() on ignored signals will wait indefinitely.  Ignored signals are dropped immediately by the system, before delivery to a waiting process.

`chan-signal` mechanism is spawning watcher thread, wait with `sigwait`, and send `Signal` to `chan`.
However, `sigwait` ignore `SIGWINCH`, and it will never be sent to `chan`.

I'm using macOS, and I'm not sure this is also problem in linux.

The easiest way to resolve this is set the empty signal handler for ignored signals.
But this might cause other problems.
Is there any other way to resolve this?

**Comment by skull-squadron** [comment]
Confirmed, this is a show-stopper problem. We need `WINCH` and it should work. If it cannot catch these signals, it should not compile, but it should also be fixed. Silently broken is unprofessional fail.


@agatan Obviously, if you bothered to read the man pages, a correct call to `pthread_sigmask` is needed. A catchable signal must be not blocked, not ignored and have a registered handler to deliver it to.

**Comment by euclio** [comment]
I just ran into this as well. I don't understand, is this something that is fixable given the current architecture of the crate? I could try and open a PR.

**Comment by Timmmm** [comment]
Just run into this too. I think you are both right. You need to set the signals to be "blocked" and also not "ignored.

From `man sigwait`:

> The signals specified by set should be blocked, but not ignored, at the time of the call to sigwait().
>
> Processes which call sigwait() on ignored signals will wait indefinitely.  Ignored signals are dropped immediately by the system, before delivery to a waiting process.

From `man sigaction`:

> A process may specify a handler to which a signal is delivered, or specify that a signal is to be ignored. 

From `man pthread_sigmask`:

Actually these man pages are about the most confusingly written I have ever read, but `pthread_sigmask` lets you set the "block" bit on a signal.

It would be good if this crate's `Readme.md` would mention that it doesn't... really.. work :-/

**Comment by Timmmm** [comment]
And upon reading the code it seems like it does block the signals properly, but just doesn't set any signal handlers.

A workaround in your code is something like this:

```
extern crate libc;
use libc::sighandler_t;
use libc::{c_int, c_void, SIGWINCH};
use libc::signal;

extern fn handler(_: c_int) {}

fn get_handler() -> sighandler_t {
    handler as extern fn(c_int) as *mut c_void as sighandler_t
}

fn main() {
	unsafe { signal(SIGWINCH, get_handler()); }
...
```

I have verified that this works and I now receive `SIGNWINCH`, however this should really be fixed in the library by doing the above for any signals the user requests.

**Comment by BurntSushi** [comment]
This crate is now deprecated. See: https://users.rust-lang.org/t/ann-chan-is-deprecated-use-crossbeam-channel-instead/19251
