### ISSUE TITLE
Using chan_signal::notify masks all signals

### ISSUE THREAD

**Issue by dagit** [BurntSushi/chan-signal#2]
Consider this program:

```
#[macro_use]
extern crate chan;
extern crate chan_signal;

use chan::Receiver;
use chan_signal::Signal;

fn signal_received(rec: &Receiver<Signal>) -> bool
{
  chan_select! {
    default         => { return false },
    rec.recv() -> _ => { return true  }
  }
}

fn main() {
    // Signal gets a value when the OS sent a INT or TERM signal.
    let signal = chan_signal::notify(&[Signal::ILL]);

    // Wait for a signal or for work to be done.
    loop {
      let ret = signal_received(&signal);
      if ret {
        println!("illegal instruction");
        break
      }
    }
}
```

When I run this it only responds to `SIGILL` and `SIGKILL`. It effectively ignores all other signals. This came as a surprise since only `SIGILL` is given to `notify`. I would have expected the other signals to work as normal.

**Comment by BurntSushi** [comment]
I'd be happy to entertain alternative designs or additions to the current API. At the moment, a fixed set of channels are blocked on the initial call to `notify` so that any subsequent calls to `notify` work correctly. Probably this isn't strictly required.

**Comment by birkenfeld** [comment]
This is definitely unexpected (I was wondering why setting a SIGINT handler made the program ignore SIGTERM). Please consider lifting this restriction.
