### ISSUE TITLE
Allow Setting signals to default handling as well as ignoring them

### ISSUE THREAD

**Issue by Kilobyte22** [BurntSushi/chan-signal#4]
The way i imagine this is somewhat hard due to some design choices, and in most cases this would probably be a breaking change. My proposel would be the following

``` rust
// Handle SIGTERM. channel is the writing end of the channel
chan_signal::handle([Signal::TERM], Handle(channel));
// We don't care about SIGINT
chan_signal::handle([Signal::INT], Ignore);
// Someone else has messed with SIGSEGV - lets teach them a lesson
chan_signal::handle([Signal::SEGV], Default);
```

Implementing this would also fix #2

**Comment by BurntSushi** [comment]
FWIW, given the youth of this library, breaking changes with an appropriate version bump is totally acceptable. I'd even happily entertain a complete rewrite.

**Comment by BurntSushi** [comment]
This crate is now deprecated. See: https://users.rust-lang.org/t/ann-chan-is-deprecated-use-crossbeam-channel-instead/19251
